version: '3.8'

services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    environment:
      - AUTH_SERVICE_URL=http://auth-service:3001
      - COURSES_SERVICE_URL=http://courses-service:3002
      - GATEWAY_SECRET=${GATEWAY_SECRET}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=3000
    depends_on:
      - auth-service
    networks:
      - lms-network

  auth-service:
    build: ./auth-service
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}?schema=public
      - JWT_SECRET=${JWT_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - GATEWAY_SECRET=${GATEWAY_SECRET}
      - PORT=3001
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - lms-network

  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - lms-network

volumes:
  postgres_data:

networks:
  lms-network:
    driver: bridge 